# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\",\n\x05Point\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\"I\n\tRectangle\x12\x1d\n\x02lo\x18\x01 \x01(\x0b\x32\x11.helloworld.Point\x12\x1d\n\x02hi\x18\x02 \x01(\x0b\x32\x11.helloworld.Point\"<\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x08location\x18\x02 \x01(\x0b\x32\x11.helloworld.Point\"A\n\tRouteNote\x12#\n\x08location\x18\x01 \x01(\x0b\x32\x11.helloworld.Point\x12\x0f\n\x07message\x18\x02 \x01(\t\"b\n\x0cRouteSummary\x12\x13\n\x0bpoint_count\x18\x01 \x01(\x05\x12\x15\n\rfeature_count\x18\x02 \x01(\x05\x12\x10\n\x08\x64istance\x18\x03 \x01(\x05\x12\x14\n\x0c\x65lapsed_time\x18\x04 \x01(\x05\x32\x8a\x02\n\x07Greeter\x12>\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\"\x00\x12>\n\x0cListFeatures\x12\x15.helloworld.Rectangle\x1a\x13.helloworld.Feature\"\x00\x30\x01\x12>\n\x0bRecordRoute\x12\x11.helloworld.Point\x1a\x18.helloworld.RouteSummary\"\x00(\x01\x12?\n\tRouteChat\x12\x15.helloworld.RouteNote\x1a\x15.helloworld.RouteNote\"\x00(\x01\x30\x01\x42X\n\x16io.grpc.examples.protoB\x0fHelloWorldProtoP\x01Z+google.golang.org/grpc/examples/proto/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026io.grpc.examples.protoB\017HelloWorldProtoP\001Z+google.golang.org/grpc/examples/proto/proto'
  _HELLOREQUEST._serialized_start=32
  _HELLOREQUEST._serialized_end=60
  _HELLOREPLY._serialized_start=62
  _HELLOREPLY._serialized_end=91
  _POINT._serialized_start=93
  _POINT._serialized_end=137
  _RECTANGLE._serialized_start=139
  _RECTANGLE._serialized_end=212
  _FEATURE._serialized_start=214
  _FEATURE._serialized_end=274
  _ROUTENOTE._serialized_start=276
  _ROUTENOTE._serialized_end=341
  _ROUTESUMMARY._serialized_start=343
  _ROUTESUMMARY._serialized_end=441
  _GREETER._serialized_start=444
  _GREETER._serialized_end=710
# @@protoc_insertion_point(module_scope)
